services:
  postgres:
    image: postgres:15-alpine
    container_name: zelda-postgres
    environment:
      POSTGRES_DB: zelda_weapons_db
      POSTGRES_USER: zelda_user
      POSTGRES_PASSWORD: zelda_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zelda_user -d zelda_weapons_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zelda-network

  app:
    build: .
    container_name: zelda-api
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zelda_weapons_db
      SPRING_DATASOURCE_USERNAME: zelda_user
      SPRING_DATASOURCE_PASSWORD: zelda_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
    networks:
      - zelda-network

volumes:
  postgres_data:

networks:
  zelda-network:
    driver: bridge