//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.12 at 06:33:27 PM GMT 
//


package com.zelda.weapons.ws;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for element.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="element"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Fire"/&gt;
 *     &lt;enumeration value="Ice"/&gt;
 *     &lt;enumeration value="Electric"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "element")
@XmlEnum
public enum Element {

    @XmlEnumValue("Fire")
    FIRE("Fire"),
    @XmlEnumValue("Ice")
    ICE("Ice"),
    @XmlEnumValue("Electric")
    ELECTRIC("Electric");
    private final String value;

    Element(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Element fromValue(String v) {
        for (Element c: Element.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
