//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.12 at 06:33:27 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://weapons.zelda.com/ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zelda.weapons.ws;
